name: Teacher Workout Workflow

on: 

  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Run unit tests
      run: xcodebuild test -scheme 'Teacher Workout' -project 'Teacher Workout.xcodeproj' -destination 'platform=iOS Simulator,name=iPhone 12'
